name: 꼼꼼한 재은씨의 블로그
description: '꼼꼼한 재은씨(jaeeun.lee@devsisters.com)'
meta_description: 당신을 개발자로 만들어 드립니다.
markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: UA-XXXXXXXX-X
plugins:
  - jekyll-paginate
url: ''
author: SQLPRO
disqus-shortname: ''
google_fonts: "Nanum+Gothic:400, 700"
site: 
  name: '재은이의 행복한 블로그'